app:
  build: .
  environment:
    - LOG_LEVEL=debug
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - RABBIT_HOST=rabbitmq
  links:
    - redis
    - rabbitmq

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 15672:15672
    - 5672:5672

redis:
  image: redis:latest
  ports:
    - 6379
